GET http://localhost:5000/elastic?index=planinternational HTTP/1.1
content-type: application/json

{
  "explain": true,
  "_source": {
    "include": [
      "title",
      "icon",
      "processed",
      "creationDate",
      "template",
      "metadata",
      "suggestedMetadata",
      "type",
      "sharedId",
      "toc",
      "attachments",
      "language",
      "file",
      "uploaded",
      "published",
      "relationships"
    ]
  },
  "from": 0,
  "size": "30",
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "should": []
          }
        }
      ],
      "must_not": [],
      "filter": [
        {
          "term": {
            "published": true
          }
        },
        {
          "terms": {
            "template": [
              "5d305622ad878e81d220b324"
            ]
          }
        },
        {
          "term": {
            "language": "es"
          }
        },
        {
          "bool": {
            "should": [
              {
                "term": {
                    "suggestedMetadata.themes.value.raw": "jv3j3veplsp"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "sort": [
    "_score"
  ]
}
