GET http://localhost:5000/elastic?index=planinternational HTTP/1.1
content-type: application/json

{
  "explain": true,
  "_source": {
    "include": [
      "title",
      "icon",
      "processed",
      "creationDate",
      "template",
      "metadata",
      "type",
      "sharedId",
      "toc",
      "attachments",
      "language",
      "file",
      "uploaded",
      "published",
      "relationships"
    ]
  },
  "from": 0,
  "size": "30",
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "should": []
          }
        }
      ],
      "must_not": [],
      "filter": [
        {
          "term": {
            "published": true
          }
        },
        {
          "terms": {
            "template": [
              "5d305622ad878e81d220b324"
            ]
          }
        },
        {
          "term": {
            "language": "es"
          }
        },
        {
          "bool": {
            "should": [
              {
                "nested": {
                  "path": "metadata.themes",
                  "query": {
                    "bool": {
                      "must": [
                        {
                          "term": {
                            "metadata.themes.value.raw": "jv3j3veplsp"
                          }
                        },
                        {
                          "term": {
                            "metadata.themes.is_suggested": true
                          }
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  },
  "sort": [
    "_score"
  ],
  "aggregations": {
    "all": {
      "global": {},
      "aggregations": {
        "_types": {
          "terms": {
            "field": "template.raw",
            "missing": "missing",
            "size": 9999
          },
          "aggregations": {
            "filtered": {
              "filter": {
                "bool": {
                  "must": [
                    {
                      "bool": {
                        "should": []
                      }
                    },
                    {
                      "term": {
                        "language": "es"
                      }
                    }
                  ],
                  "filter": [
                    {
                      "match": {
                        "published": true
                      }
                    },
                    {
                      "bool": {
                        "should": [
                          {
                            "nested": {
                              "path": "metadata.themes",
                              "query": {
                                "bool": {
                                  "must": [
                                    {
                                      "term": {
                                        "metadata.themes.value.raw": "jv3j3veplsp"
                                      }
                                    },
                                    {
                                      "term": {
                                        "metadata.themes.is_suggested": true
                                      }
                                    }
                                  ]
                                }
                              }
                            }
                          }
                        ]
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "legal_status.value": {
          "nested": {
            "path": "metadata.legal_status"
          },
              "aggregations": {
                "filtered": {
                  "filter": {
                    "bool": {
                      "filter": [
                        {
                          "term": {
                            "published": true
                          }
                        },
                        {
                          "terms": {
                            "template": [
                              "5d305622ad878e81d220b324"
                            ]
                          }
                        },
                        {
                          "term": {
                            "language": "es"
                          }
                        },
                        {
                          "bool": {
                            "should": [
                              {
                                "nested": {
                                  "path": "metadata.themes",
                                  "query": {
                                    "bool": {
                                      "must": [
                                        {
                                          "term": {
                                            "metadata.themes.value.raw": "jv3j3veplsp"
                                          }
                                        },
                                        {
                                          "term": {
                                            "metadata.themes.is_suggested": true
                                          }
                                        }
                                      ]
                                    }
                                  }
                                }
                              }
                            ]
                          }
                        },
                        {
                          "bool": {
                            "should": []
                          }
                        }
                      ]
                    }
                  }
                }
              }
        
          
        },
        "body": {
          "nested": {
            "path": "metadata.body"
          },
          "aggregations": {
            "value": {
              "terms": {
                "field": "metadata.body.value.raw",
                "missing": "missing",
                "size": 9999
              },
              "aggregations": {
                "filtered": {
                  "filter": {
                    "bool": {
                      "filter": [
                        {
                          "term": {
                            "published": true
                          }
                        },
                        {
                          "terms": {
                            "template": [
                              "5d305622ad878e81d220b324"
                            ]
                          }
                        },
                        {
                          "term": {
                            "language": "es"
                          }
                        },
                        {
                          "bool": {
                            "should": [
                              {
                                "nested": {
                                  "path": "metadata.themes",
                                  "query": {
                                    "bool": {
                                      "must": [
                                        {
                                          "term": {
                                            "metadata.themes.value.raw": "jv3j3veplsp"
                                          }
                                        },
                                        {
                                          "term": {
                                            "metadata.themes.is_suggested": true
                                          }
                                        }
                                      ]
                                    }
                                  }
                                }
                              }
                            ]
                          }
                        },
                        {
                          "bool": {
                            "should": []
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "document_type": {
          "nested": {
            "path": "metadata.document_type"
          },
          "aggregations": {
            "value": {
              "terms": {
                "field": "metadata.document_type.value.raw",
                "missing": "missing",
                "size": 9999
              },
              "aggregations": {
                "filtered": {
                  "filter": {
                    "bool": {
                      "filter": [
                        {
                          "term": {
                            "published": true
                          }
                        },
                        {
                          "terms": {
                            "template": [
                              "5d305622ad878e81d220b324"
                            ]
                          }
                        },
                        {
                          "term": {
                            "language": "es"
                          }
                        },
                        {
                          "bool": {
                            "should": [
                              {
                                "nested": {
                                  "path": "metadata.themes",
                                  "query": {
                                    "bool": {
                                      "must": [
                                        {
                                          "term": {
                                            "metadata.themes.value.raw": "jv3j3veplsp"
                                          }
                                        },
                                        {
                                          "term": {
                                            "metadata.themes.is_suggested": true
                                          }
                                        }
                                      ]
                                    }
                                  }
                                }
                              }
                            ]
                          }
                        },
                        {
                          "bool": {
                            "should": []
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "means_of_adoption": {
          "nested": {
            "path": "metadata.means_of_adoption"
          },
          "aggregations": {
            "value": {
              "terms": {
                "field": "metadata.means_of_adoption.value.raw",
                "missing": "missing",
                "size": 9999
              },
              "aggregations": {
                "filtered": {
                  "filter": {
                    "bool": {
                      "filter": [
                        {
                          "term": {
                            "published": true
                          }
                        },
                        {
                          "terms": {
                            "template": [
                              "5d305622ad878e81d220b324"
                            ]
                          }
                        },
                        {
                          "term": {
                            "language": "es"
                          }
                        },
                        {
                          "bool": {
                            "should": [
                              {
                                "nested": {
                                  "path": "metadata.themes",
                                  "query": {
                                    "bool": {
                                      "must": [
                                        {
                                          "term": {
                                            "metadata.themes.value.raw": "jv3j3veplsp"
                                          }
                                        },
                                        {
                                          "term": {
                                            "metadata.themes.is_suggested": true
                                          }
                                        }
                                      ]
                                    }
                                  }
                                }
                              }
                            ]
                          }
                        },
                        {
                          "bool": {
                            "should": []
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "paragraph_type": {
          "nested": {
            "path": "metadata.paragraph_type"
          },
          "aggregations": {
            "value": {
              "terms": {
                "field": "metadata.paragraph_type.value.raw",
                "missing": "missing",
                "size": 9999
              },
              "aggregations": {
                "filtered": {
                  "filter": {
                    "bool": {
                      "filter": [
                        {
                          "term": {
                            "published": true
                          }
                        },
                        {
                          "terms": {
                            "template": [
                              "5d305622ad878e81d220b324"
                            ]
                          }
                        },
                        {
                          "term": {
                            "language": "es"
                          }
                        },
                        {
                          "bool": {
                            "should": [
                              {
                                "nested": {
                                  "path": "metadata.themes",
                                  "query": {
                                    "bool": {
                                      "must": [
                                        {
                                          "term": {
                                            "metadata.themes.value.raw": "jv3j3veplsp"
                                          }
                                        },
                                        {
                                          "term": {
                                            "metadata.themes.is_suggested": true
                                          }
                                        }
                                      ]
                                    }
                                  }
                                }
                              }
                            ]
                          }
                        },
                        {
                          "bool": {
                            "should": []
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "themes": {
          "nested": {
            "path": "metadata.themes"
          },
          "aggregations": {
            "value": {
              "terms": {
                "field": "metadata.themes.value.raw",
                "missing": "missing",
                "size": 9999
              },
              "aggregations": {
                "filtered": {
                  "filter": {
                    "bool": {
                      "filter": [
                        {
                          "term": {
                            "published": true
                          }
                        },
                        {
                          "terms": {
                            "template": [
                              "5d305622ad878e81d220b324"
                            ]
                          }
                        },
                        {
                          "term": {
                            "language": "es"
                          }
                        },
                        {
                          "bool": {
                            "should": []
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "affected_persons": {
          "nested": {
            "path": "metadata.affected_persons"
          },
          "aggregations": {
            "value": {
              "terms": {
                "field": "metadata.affected_persons.value.raw",
                "missing": "missing",
                "size": 9999
              },
              "aggregations": {
                "filtered": {
                  "filter": {
                    "bool": {
                      "filter": [
                        {
                          "term": {
                            "published": true
                          }
                        },
                        {
                          "terms": {
                            "template": [
                              "5d305622ad878e81d220b324"
                            ]
                          }
                        },
                        {
                          "term": {
                            "language": "es"
                          }
                        },
                        {
                          "bool": {
                            "should": [
                              {
                                "nested": {
                                  "path": "metadata.themes",
                                  "query": {
                                    "bool": {
                                      "must": [
                                        {
                                          "term": {
                                            "metadata.themes.value.raw": "jv3j3veplsp"
                                          }
                                        },
                                        {
                                          "term": {
                                            "metadata.themes.is_suggested": true
                                          }
                                        }
                                      ]
                                    }
                                  }
                                }
                              }
                            ]
                          }
                        },
                        {
                          "bool": {
                            "should": []
                          }
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
