GET http://localhost:5000/elastic?index=planinternational HTTP/1.1
content-type: application/json

{
  "explain": true,
  "_source": {
    "include": [
      "title",
      "icon",
      "processed",
      "creationDate",
      "template",
      "metadata",
      "type",
      "sharedId",
      "toc",
      "attachments",
      "language",
      "file",
      "uploaded",
      "published",
      "relationships"
    ]
  },
  "from": 0,
  "size": "30",
  "query": {
    "bool": {
      "must": [
        {
          "bool": {
            "should": []
          }
        }
      ],
      "must_not": [],
      "filter": [
        {
          "term": {
            "published": true
          }
        },
        {
          "terms": {
            "template": [
              "5d305622ad878e81d220b324"
            ]
          }
        },
        {
          "term": {
            "language": "en"
          }
        },
        {"bool": { "must": [
        {
          "terms": {
            "metadata.themes.value.raw": [
              "mxxa4cvx4v"
            ]
          }
        },
        {
          "bool": {
            "should": [{
              "term": {
                "metadata.themes.is_suggested": false
              }
            },
            {"bool": {
            "must_not": [{
              "exists": {"field": "metadata.themes.is_suggested"}
            }]}}
            ]
          }
        }]}}
      ]
    }
  },
  "sort": [
    {
      "creationDate.sort": {
        "order": "desc",
        "unmapped_type": "boolean"
      }
    }
  ],
  "aggregations": {
    "all": {
      "global": {},
      "aggregations": {
        "_types": {
          "terms": {
            "field": "template.raw",
            "missing": "missing",
            "size": 9999
          },
          "aggregations": {
            "filtered": {
              "filter": {
                "bool": {
                  "must": [
                    {
                      "bool": {
                        "should": []
                      }
                    },
                    {
                      "term": {
                        "language": "es"
                      }
                    }
                  ],
                  "filter": [
                    {
                      "match": {
                        "published": true
                      }
                    },
                    {
                      "terms": {
                        "metadata.themes.value.raw": [
                          "km72d10gpd"
                        ]
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "legal_status.value": {
          "terms": {
            "field": "metadata.legal_status.value.raw",
            "missing": "missing",
            "size": 9999
          },
          "aggregations": {
            "filtered": {
              "filter": {
                "bool": {
                  "filter": [
                    {
                      "term": {
                        "published": true
                      }
                    },
                    {
                      "terms": {
                        "template": [
                          "5d305622ad878e81d220b324"
                        ]
                      }
                    },
                    {
                      "term": {
                        "language": "es"
                      }
                    },
                    {
                      "terms": {
                        "metadata.themes.value.raw": [
                          "km72d10gpd"
                        ]
                      }
                    },
                    {
                      "bool": {
                        "should": []
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "body.value": {
          "terms": {
            "field": "metadata.body.value.raw",
            "missing": "missing",
            "size": 9999
          },
          "aggregations": {
            "filtered": {
              "filter": {
                "bool": {
                  "filter": [
                    {
                      "term": {
                        "published": true
                      }
                    },
                    {
                      "terms": {
                        "template": [
                          "5d305622ad878e81d220b324"
                        ]
                      }
                    },
                    {
                      "term": {
                        "language": "es"
                      }
                    },
                    {
                      "terms": {
                        "metadata.themes.value.raw": [
                          "km72d10gpd"
                        ]
                      }
                    },
                    {
                      "bool": {
                        "should": []
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "document_type.value": {
          "terms": {
            "field": "metadata.document_type.value.raw",
            "missing": "missing",
            "size": 9999
          },
          "aggregations": {
            "filtered": {
              "filter": {
                "bool": {
                  "filter": [
                    {
                      "term": {
                        "published": true
                      }
                    },
                    {
                      "terms": {
                        "template": [
                          "5d305622ad878e81d220b324"
                        ]
                      }
                    },
                    {
                      "term": {
                        "language": "es"
                      }
                    },
                    {
                      "terms": {
                        "metadata.themes.value.raw": [
                          "km72d10gpd"
                        ]
                      }
                    },
                    {
                      "bool": {
                        "should": []
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "means_of_adoption.value": {
          "terms": {
            "field": "metadata.means_of_adoption.value.raw",
            "missing": "missing",
            "size": 9999
          },
          "aggregations": {
            "filtered": {
              "filter": {
                "bool": {
                  "filter": [
                    {
                      "term": {
                        "published": true
                      }
                    },
                    {
                      "terms": {
                        "template": [
                          "5d305622ad878e81d220b324"
                        ]
                      }
                    },
                    {
                      "term": {
                        "language": "es"
                      }
                    },
                    {
                      "terms": {
                        "metadata.themes.value.raw": [
                          "km72d10gpd"
                        ]
                      }
                    },
                    {
                      "bool": {
                        "should": []
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "paragraph_type.value": {
          "terms": {
            "field": "metadata.paragraph_type.value.raw",
            "missing": "missing",
            "size": 9999
          },
          "aggregations": {
            "filtered": {
              "filter": {
                "bool": {
                  "filter": [
                    {
                      "term": {
                        "published": true
                      }
                    },
                    {
                      "terms": {
                        "template": [
                          "5d305622ad878e81d220b324"
                        ]
                      }
                    },
                    {
                      "term": {
                        "language": "es"
                      }
                    },
                    {
                      "terms": {
                        "metadata.themes.value.raw": [
                          "km72d10gpd"
                        ]
                      }
                    },
                    {
                      "bool": {
                        "should": []
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "themes.value": {
          "terms": {
            "field": "metadata.themes.value.raw",
            "missing": "missing",
            "size": 9999
          },
          "aggregations": {
            "filtered": {
              "filter": {
                "bool": {
                  "filter": [
                    {
                      "term": {
                        "published": true
                      }
                    },
                    {
                      "terms": {
                        "template": [
                          "5d305622ad878e81d220b324"
                        ]
                      }
                    },
                    {
                      "term": {
                        "language": "es"
                      }
                    },
                    {
                      "bool": {
                        "should": []
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "affected_persons.value": {
          "terms": {
            "field": "metadata.affected_persons.value.raw",
            "missing": "missing",
            "size": 9999
          },
          "aggregations": {
            "filtered": {
              "filter": {
                "bool": {
                  "filter": [
                    {
                      "term": {
                        "published": true
                      }
                    },
                    {
                      "terms": {
                        "template": [
                          "5d305622ad878e81d220b324"
                        ]
                      }
                    },
                    {
                      "term": {
                        "language": "es"
                      }
                    },
                    {
                      "terms": {
                        "metadata.themes.value.raw": [
                          "km72d10gpd"
                        ]
                      }
                    },
                    {
                      "bool": {
                        "should": []
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    }
  }
}
